volumes:
  portfolio_vol:

services:
  portfolio_app: 
    image: sarojdockerworkspace/portfolio_app:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app 
    ports:
      - 5173:5173
    volumes: 
      - .:/portfolio/fortend
      - portfolio_vol:/portfolio/fortend/node_modules
    command: > 
      sh -c " npm install && npm run dev "